const { PNG } = require('pngjs');
const fs = require('fs');
const path = require('path');

const TILE_SIZE = 32;
const CREATURE_SIZE = 64;

// Utility to create a PNG with pixel data
function createPNG(width, height, pixels) {
  const png = new PNG({ width, height });

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const idx = (width * y + x) << 2;
      const pixelIdx = y * width + x;
      const color = pixels[pixelIdx] || [0, 0, 0, 0];

      png.data[idx] = color[0];     // R
      png.data[idx + 1] = color[1]; // G
      png.data[idx + 2] = color[2]; // B
      png.data[idx + 3] = color[3] !== undefined ? color[3] : 255; // A
    }
  }

  return png;
}

// Save PNG to file
function savePNG(png, filepath) {
  const dir = path.dirname(filepath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  const buffer = PNG.sync.write(png);
  fs.writeFileSync(filepath, buffer);
  console.log(`Created: ${filepath}`);
}

// Fill rectangle in pixel array
function fillRect(pixels, width, x, y, w, h, color) {
  for (let py = y; py < y + h; py++) {
    for (let px = x; px < x + w; px++) {
      if (px >= 0 && px < width && py >= 0) {
        pixels[py * width + px] = color;
      }
    }
  }
}

// Draw pixel art from a pattern string
function drawPattern(pixels, width, startX, startY, pattern, palette) {
  const lines = pattern.trim().split('\n');
  lines.forEach((line, y) => {
    [...line].forEach((char, x) => {
      if (palette[char]) {
        pixels[(startY + y) * width + (startX + x)] = palette[char];
      }
    });
  });
}

// ============ TILE SPRITES ============

function createGrassTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const green1 = [76, 153, 76, 255];    // Base green
  const green2 = [92, 172, 92, 255];    // Lighter green
  const green3 = [60, 130, 60, 255];    // Darker green
  const green4 = [100, 180, 100, 255];  // Highlight

  // Base color with slight variation
  for (let y = 0; y < TILE_SIZE; y++) {
    for (let x = 0; x < TILE_SIZE; x++) {
      const noise = Math.random();
      if (noise < 0.6) {
        pixels[y * TILE_SIZE + x] = green1;
      } else if (noise < 0.8) {
        pixels[y * TILE_SIZE + x] = green2;
      } else if (noise < 0.95) {
        pixels[y * TILE_SIZE + x] = green3;
      } else {
        pixels[y * TILE_SIZE + x] = green4;
      }
    }
  }

  // Add small grass tufts
  for (let i = 0; i < 8; i++) {
    const x = 4 + (i % 4) * 7 + Math.floor(Math.random() * 3);
    const y = 4 + Math.floor(i / 4) * 14 + Math.floor(Math.random() * 4);
    if (x < TILE_SIZE - 1 && y < TILE_SIZE - 2) {
      pixels[y * TILE_SIZE + x] = green3;
      pixels[(y + 1) * TILE_SIZE + x] = green3;
      pixels[y * TILE_SIZE + x + 1] = green4;
    }
  }

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/grass.png');
}

function createTallGrassTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const base = [60, 130, 60, 255];      // Base grass
  const blade1 = [40, 100, 40, 255];    // Dark blade
  const blade2 = [70, 150, 70, 255];    // Light blade
  const tip = [90, 170, 90, 255];       // Bright tip
  const shadow = [35, 85, 35, 255];     // Shadow

  // Base grass texture
  for (let y = 0; y < TILE_SIZE; y++) {
    for (let x = 0; x < TILE_SIZE; x++) {
      pixels[y * TILE_SIZE + x] = Math.random() > 0.3 ? base : blade2;
    }
  }

  // Draw tall grass blades in a natural pattern
  const bladePositions = [2, 6, 10, 15, 19, 23, 27];
  bladePositions.forEach((startX, i) => {
    const height = 12 + Math.floor(Math.random() * 8);
    const sway = (i % 2 === 0) ? 1 : -1;

    for (let h = 0; h < height; h++) {
      const y = TILE_SIZE - 4 - h;
      const x = startX + (h > height - 4 ? sway : 0);

      if (x >= 0 && x < TILE_SIZE && y >= 0 && y < TILE_SIZE) {
        pixels[y * TILE_SIZE + x] = h < 3 ? shadow : blade1;
        if (x + 1 < TILE_SIZE) {
          pixels[y * TILE_SIZE + x + 1] = h > height - 3 ? tip : blade2;
        }
      }
    }
  });

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/tallGrass.png');
}

function createPathTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const sand1 = [194, 164, 128, 255];   // Base sand
  const sand2 = [180, 150, 115, 255];   // Darker sand
  const sand3 = [210, 180, 145, 255];   // Lighter sand
  const pebble = [160, 135, 105, 255];  // Pebble
  const highlight = [225, 200, 165, 255]; // Highlight

  // Base texture with noise
  for (let y = 0; y < TILE_SIZE; y++) {
    for (let x = 0; x < TILE_SIZE; x++) {
      const noise = Math.random();
      if (noise < 0.5) {
        pixels[y * TILE_SIZE + x] = sand1;
      } else if (noise < 0.75) {
        pixels[y * TILE_SIZE + x] = sand2;
      } else if (noise < 0.9) {
        pixels[y * TILE_SIZE + x] = sand3;
      } else {
        pixels[y * TILE_SIZE + x] = highlight;
      }
    }
  }

  // Add small pebbles
  for (let i = 0; i < 12; i++) {
    const x = Math.floor(Math.random() * (TILE_SIZE - 2)) + 1;
    const y = Math.floor(Math.random() * (TILE_SIZE - 2)) + 1;
    pixels[y * TILE_SIZE + x] = pebble;
    if (Math.random() > 0.5 && x + 1 < TILE_SIZE) {
      pixels[y * TILE_SIZE + x + 1] = pebble;
    }
  }

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/path.png');
}

function createWaterTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const water1 = [50, 120, 200, 255];   // Deep blue
  const water2 = [70, 140, 220, 255];   // Medium blue
  const water3 = [90, 160, 235, 255];   // Light blue
  const shine = [150, 200, 255, 255];   // Highlight
  const foam = [200, 230, 255, 255];    // Foam white

  // Base water with gradient feel
  for (let y = 0; y < TILE_SIZE; y++) {
    for (let x = 0; x < TILE_SIZE; x++) {
      const wave = Math.sin((x * 0.4) + (y * 0.2)) * 0.5 + 0.5;
      if (wave < 0.3) {
        pixels[y * TILE_SIZE + x] = water1;
      } else if (wave < 0.6) {
        pixels[y * TILE_SIZE + x] = water2;
      } else {
        pixels[y * TILE_SIZE + x] = water3;
      }
    }
  }

  // Add wave lines
  for (let waveY = 4; waveY < TILE_SIZE; waveY += 10) {
    for (let x = 0; x < TILE_SIZE; x++) {
      const offset = Math.floor(Math.sin(x * 0.3) * 2);
      const y = waveY + offset;
      if (y >= 0 && y < TILE_SIZE) {
        pixels[y * TILE_SIZE + x] = shine;
        if (y + 1 < TILE_SIZE) {
          pixels[(y + 1) * TILE_SIZE + x] = foam;
        }
      }
    }
  }

  // Add sparkles
  for (let i = 0; i < 5; i++) {
    const x = Math.floor(Math.random() * TILE_SIZE);
    const y = Math.floor(Math.random() * TILE_SIZE);
    pixels[y * TILE_SIZE + x] = foam;
  }

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/water.png');
}

function createWallTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const stone1 = [120, 115, 130, 255];  // Base stone
  const stone2 = [100, 95, 110, 255];   // Dark stone
  const stone3 = [140, 135, 150, 255];  // Light stone
  const highlight = [160, 155, 170, 255]; // Highlight
  const mortar = [80, 75, 90, 255];     // Dark mortar

  fillRect(pixels, TILE_SIZE, 0, 0, TILE_SIZE, TILE_SIZE, mortar);

  // Draw stone brick pattern
  const brickH = 7;
  const brickW = 14;

  for (let row = 0; row < 5; row++) {
    const offset = (row % 2) * 8;
    for (let col = -1; col < 4; col++) {
      const x = col * (brickW + 2) + offset;
      const y = row * (brickH + 2) - 1;

      // Main stone
      fillRect(pixels, TILE_SIZE, x + 1, y + 1, brickW, brickH, stone1);

      // Top highlight
      fillRect(pixels, TILE_SIZE, x + 1, y + 1, brickW, 2, stone3);
      fillRect(pixels, TILE_SIZE, x + 1, y + 1, 2, brickH, stone3);

      // Bottom shadow
      fillRect(pixels, TILE_SIZE, x + 1, y + brickH - 1, brickW, 2, stone2);
      fillRect(pixels, TILE_SIZE, x + brickW - 1, y + 1, 2, brickH, stone2);

      // Random texture
      for (let py = y + 2; py < y + brickH - 1; py++) {
        for (let px = x + 2; px < x + brickW - 1; px++) {
          if (px >= 0 && px < TILE_SIZE && py >= 0 && py < TILE_SIZE) {
            if (Math.random() > 0.85) {
              pixels[py * TILE_SIZE + px] = Math.random() > 0.5 ? stone2 : highlight;
            }
          }
        }
      }
    }
  }

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/wall.png');
}

// ============ PLAYER SPRITE ============

function createPlayerSprite() {
  const width = TILE_SIZE * 4;  // 4 frames
  const height = TILE_SIZE * 4; // 4 directions
  const pixels = new Array(width * height).fill([0, 0, 0, 0]);

  const skin = [255, 206, 180, 255];
  const hair = [60, 40, 20, 255];
  const shirt = [65, 105, 225, 255];
  const shirtLight = [90, 130, 240, 255];
  const pants = [50, 50, 80, 255];
  const pantsLight = [70, 70, 100, 255];
  const shoes = [40, 30, 20, 255];
  const outline = [30, 30, 30, 255];

  const palette = {
    '.': null, // transparent
    'o': outline,
    's': skin,
    'h': hair,
    't': shirt,
    'T': shirtLight,
    'p': pants,
    'P': pantsLight,
    'x': shoes,
  };

  // Down-facing frames (row 0) - 4 frames of walk animation
  // Frame 0: Standing
  const downFrame0 = `
................................
................................
..........oooooooo..............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
..........osssssso..............
..........osssssso..............
.........ossosossso.............
.........osssssssso.............
..........osssssso..............
...........oTttTo...............
..........oTtttTto..............
..........otttttto..............
..........otttttto..............
...........opPppo...............
...........oppppo...............
...........oppppo...............
...........opo.opo..............
...........oxo.oxo..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  // Frame 1: Right leg forward
  const downFrame1 = `
................................
................................
..........oooooooo..............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
..........osssssso..............
..........osssssso..............
.........ossosossso.............
.........osssssssso.............
..........osssssso..............
...........oTttTo...............
..........oTtttTto..............
..........otttttto..............
..........otttttto..............
...........opPppo...............
...........oppppo...............
..........opo.oppo..............
..........oxo..opo..............
...............oxo..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  // Frame 2: Standing (same as frame 0)
  const downFrame2 = downFrame0;

  // Frame 3: Left leg forward
  const downFrame3 = `
................................
................................
..........oooooooo..............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
..........osssssso..............
..........osssssso..............
.........ossosossso.............
.........osssssssso.............
..........osssssso..............
...........oTttTo...............
..........oTtttTto..............
..........otttttto..............
..........otttttto..............
...........opPppo...............
...........oppppo...............
..........oppo.opo..............
..........opo..oxo..............
..........oxo.......................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  // Draw down-facing frames
  drawPattern(pixels, width, 0, 0, downFrame0, palette);
  drawPattern(pixels, width, TILE_SIZE, 0, downFrame1, palette);
  drawPattern(pixels, width, TILE_SIZE * 2, 0, downFrame2, palette);
  drawPattern(pixels, width, TILE_SIZE * 3, 0, downFrame3, palette);

  // Left-facing frames (row 1)
  const leftFrame0 = `
................................
................................
..........oooooo................
.........ohhhhhho...............
.........ohhhhhho...............
.........ohhhhhhho..............
..........ossssso...............
.........osossssso..............
.........osssssso...............
..........osssso................
...........ottto................
..........ottttto...............
..........otttto................
..........otttto................
...........opppo................
...........opppo................
...........opppo................
...........opopo................
...........oxoxo................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  const leftFrame1 = `
................................
................................
..........oooooo................
.........ohhhhhho...............
.........ohhhhhho...............
.........ohhhhhhho..............
..........ossssso...............
.........osossssso..............
.........osssssso...............
..........osssso................
...........ottto................
..........ottttto...............
..........otttto................
..........otttto................
...........opppo................
...........opppo................
..........opppo.................
..........opoxo.................
...........oxo..................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  const leftFrame3 = `
................................
................................
..........oooooo................
.........ohhhhhho...............
.........ohhhhhho...............
.........ohhhhhhho..............
..........ossssso...............
.........osossssso..............
.........osssssso...............
..........osssso................
...........ottto................
..........ottttto...............
..........otttto................
..........otttto................
...........opppo................
...........opppo................
...........opppo................
...........oxopo................
............oxo.................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  drawPattern(pixels, width, 0, TILE_SIZE, leftFrame0, palette);
  drawPattern(pixels, width, TILE_SIZE, TILE_SIZE, leftFrame1, palette);
  drawPattern(pixels, width, TILE_SIZE * 2, TILE_SIZE, leftFrame0, palette);
  drawPattern(pixels, width, TILE_SIZE * 3, TILE_SIZE, leftFrame3, palette);

  // Right-facing frames (row 2) - mirror of left
  const rightFrame0 = `
................................
................................
................oooooo..........
...............ohhhhhho.........
...............ohhhhhho.........
..............ohhhhhhho.........
...............ossssso..........
..............osssssoso.........
..............osssssso..........
................osssso..........
................ottto...........
...............ottttto..........
................otttto..........
................otttto..........
................opppo...........
................opppo...........
................opppo...........
................opopo...........
................oxoxo...........
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  const rightFrame1 = `
................................
................................
................oooooo..........
...............ohhhhhho.........
...............ohhhhhho.........
..............ohhhhhhho.........
...............ossssso..........
..............osssssoso.........
..............osssssso..........
................osssso..........
................ottto...........
...............ottttto..........
................otttto..........
................otttto..........
................opppo...........
................opppo...........
.................opppo..........
.................oxopo..........
..................oxo...........
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  const rightFrame3 = `
................................
................................
................oooooo..........
...............ohhhhhho.........
...............ohhhhhho.........
..............ohhhhhhho.........
...............ossssso..........
..............osssssoso.........
..............osssssso..........
................osssso..........
................ottto...........
...............ottttto..........
................otttto..........
................otttto..........
................opppo...........
................opppo...........
................opppo...........
................opoxo...........
.................oxo............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  drawPattern(pixels, width, 0, TILE_SIZE * 2, rightFrame0, palette);
  drawPattern(pixels, width, TILE_SIZE, TILE_SIZE * 2, rightFrame1, palette);
  drawPattern(pixels, width, TILE_SIZE * 2, TILE_SIZE * 2, rightFrame0, palette);
  drawPattern(pixels, width, TILE_SIZE * 3, TILE_SIZE * 2, rightFrame3, palette);

  // Up-facing frames (row 3)
  const upFrame0 = `
................................
................................
..........oooooooo..............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
..........ohhhhhho..............
..........osssssso..............
...........ottttto..............
..........oTtttTto..............
..........otttttto..............
..........otttttto..............
..........otttttto..............
...........oppppo...............
...........oppppo...............
...........oppppo...............
...........opo.opo..............
...........oxo.oxo..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  const upFrame1 = `
................................
................................
..........oooooooo..............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
..........ohhhhhho..............
..........osssssso..............
...........ottttto..............
..........oTtttTto..............
..........otttttto..............
..........otttttto..............
..........otttttto..............
...........oppppo...............
...........oppppo...............
..........opo.oppo..............
..........oxo..opo..............
...............oxo..............
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  const upFrame3 = `
................................
................................
..........oooooooo..............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
.........ohhhhhhhho.............
..........ohhhhhho..............
..........osssssso..............
...........ottttto..............
..........oTtttTto..............
..........otttttto..............
..........otttttto..............
..........otttttto..............
...........oppppo...............
...........oppppo...............
..........oppo.opo..............
..........opo..oxo..............
..........oxo.......................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;

  drawPattern(pixels, width, 0, TILE_SIZE * 3, upFrame0, palette);
  drawPattern(pixels, width, TILE_SIZE, TILE_SIZE * 3, upFrame1, palette);
  drawPattern(pixels, width, TILE_SIZE * 2, TILE_SIZE * 3, upFrame0, palette);
  drawPattern(pixels, width, TILE_SIZE * 3, TILE_SIZE * 3, upFrame3, palette);

  const png = createPNG(width, height, pixels);
  savePNG(png, 'public/assets/sprites/player/player.png');
}

// ============ CREATURE SPRITES ============

function createFlamlingSprite() {
  const size = CREATURE_SIZE;
  const pixels = new Array(size * size).fill([0, 0, 0, 0]);

  const orange = [255, 120, 50, 255];
  const red = [220, 60, 30, 255];
  const yellow = [255, 200, 50, 255];
  const white = [255, 255, 255, 255];
  const black = [20, 20, 20, 255];
  const darkOrange = [200, 80, 30, 255];

  // Body (flame-like creature)
  fillRect(pixels, size, 20, 30, 24, 26, orange);
  fillRect(pixels, size, 22, 28, 20, 4, red);
  fillRect(pixels, size, 18, 34, 28, 18, orange);
  fillRect(pixels, size, 24, 32, 16, 20, darkOrange);

  // Flame tail
  fillRect(pixels, size, 44, 36, 8, 12, yellow);
  fillRect(pixels, size, 48, 32, 6, 8, orange);
  fillRect(pixels, size, 50, 28, 4, 6, red);

  // Head
  fillRect(pixels, size, 16, 18, 20, 16, orange);
  fillRect(pixels, size, 14, 20, 24, 12, orange);

  // Eyes
  fillRect(pixels, size, 18, 22, 6, 6, white);
  fillRect(pixels, size, 28, 22, 6, 6, white);
  fillRect(pixels, size, 20, 24, 3, 3, black);
  fillRect(pixels, size, 30, 24, 3, 3, black);

  // Flame on head
  fillRect(pixels, size, 22, 10, 8, 10, yellow);
  fillRect(pixels, size, 24, 6, 4, 6, orange);
  fillRect(pixels, size, 25, 4, 2, 4, red);

  // Feet
  fillRect(pixels, size, 22, 54, 6, 6, darkOrange);
  fillRect(pixels, size, 34, 54, 6, 6, darkOrange);

  const png = createPNG(size, size, pixels);
  savePNG(png, 'public/assets/sprites/creatures/flamling.png');
}

function createAqualingSprite() {
  const size = CREATURE_SIZE;
  const pixels = new Array(size * size).fill([0, 0, 0, 0]);

  const blue = [70, 130, 220, 255];
  const lightBlue = [120, 180, 255, 255];
  const darkBlue = [40, 80, 160, 255];
  const white = [255, 255, 255, 255];
  const black = [20, 20, 20, 255];

  // Body (water drop creature)
  fillRect(pixels, size, 22, 28, 20, 28, blue);
  fillRect(pixels, size, 18, 32, 28, 20, blue);
  fillRect(pixels, size, 24, 26, 16, 4, lightBlue);

  // Head (rounded top)
  fillRect(pixels, size, 24, 18, 16, 12, blue);
  fillRect(pixels, size, 26, 14, 12, 6, blue);
  fillRect(pixels, size, 28, 12, 8, 4, lightBlue);

  // Eyes
  fillRect(pixels, size, 20, 30, 8, 8, white);
  fillRect(pixels, size, 36, 30, 8, 8, white);
  fillRect(pixels, size, 22, 32, 4, 4, black);
  fillRect(pixels, size, 38, 32, 4, 4, black);

  // Tail fin
  fillRect(pixels, size, 10, 38, 10, 8, lightBlue);
  fillRect(pixels, size, 6, 40, 6, 4, blue);

  // Side fins
  fillRect(pixels, size, 46, 34, 8, 6, lightBlue);
  fillRect(pixels, size, 48, 32, 6, 4, blue);

  // Belly shine
  fillRect(pixels, size, 26, 42, 12, 8, lightBlue);

  const png = createPNG(size, size, pixels);
  savePNG(png, 'public/assets/sprites/creatures/aqualing.png');
}

function createLeaflingSprite() {
  const size = CREATURE_SIZE;
  const pixels = new Array(size * size).fill([0, 0, 0, 0]);

  const green = [80, 180, 80, 255];
  const lightGreen = [130, 220, 130, 255];
  const darkGreen = [50, 120, 50, 255];
  const brown = [120, 80, 40, 255];
  const white = [255, 255, 255, 255];
  const black = [20, 20, 20, 255];

  // Body (plant-like)
  fillRect(pixels, size, 22, 32, 20, 24, green);
  fillRect(pixels, size, 18, 36, 28, 16, green);
  fillRect(pixels, size, 24, 34, 16, 18, lightGreen);

  // Head
  fillRect(pixels, size, 20, 22, 24, 14, green);
  fillRect(pixels, size, 22, 20, 20, 4, green);

  // Leaf on head
  fillRect(pixels, size, 28, 8, 8, 14, lightGreen);
  fillRect(pixels, size, 30, 6, 4, 4, green);
  fillRect(pixels, size, 24, 12, 6, 6, darkGreen);
  fillRect(pixels, size, 34, 12, 6, 6, darkGreen);

  // Eyes
  fillRect(pixels, size, 22, 26, 6, 6, white);
  fillRect(pixels, size, 36, 26, 6, 6, white);
  fillRect(pixels, size, 24, 28, 3, 3, black);
  fillRect(pixels, size, 38, 28, 3, 3, black);

  // Feet (root-like)
  fillRect(pixels, size, 20, 54, 8, 6, brown);
  fillRect(pixels, size, 36, 54, 8, 6, brown);
  fillRect(pixels, size, 18, 56, 4, 4, brown);
  fillRect(pixels, size, 42, 56, 4, 4, brown);

  const png = createPNG(size, size, pixels);
  savePNG(png, 'public/assets/sprites/creatures/leafling.png');
}

function createSparkitSprite() {
  const size = CREATURE_SIZE;
  const pixels = new Array(size * size).fill([0, 0, 0, 0]);

  const yellow = [255, 220, 50, 255];
  const orange = [255, 180, 30, 255];
  const white = [255, 255, 255, 255];
  const black = [20, 20, 20, 255];

  // Body (electric mouse-like)
  fillRect(pixels, size, 20, 28, 24, 24, yellow);
  fillRect(pixels, size, 18, 32, 28, 16, yellow);
  fillRect(pixels, size, 24, 30, 16, 18, orange);

  // Head
  fillRect(pixels, size, 18, 18, 28, 14, yellow);
  fillRect(pixels, size, 20, 16, 24, 4, yellow);

  // Ears (pointed)
  fillRect(pixels, size, 14, 8, 6, 12, yellow);
  fillRect(pixels, size, 44, 8, 6, 12, yellow);
  fillRect(pixels, size, 14, 6, 4, 4, black);
  fillRect(pixels, size, 46, 6, 4, 4, black);

  // Eyes
  fillRect(pixels, size, 22, 22, 6, 6, white);
  fillRect(pixels, size, 36, 22, 6, 6, white);
  fillRect(pixels, size, 24, 24, 3, 3, black);
  fillRect(pixels, size, 38, 24, 3, 3, black);

  // Cheeks (red circles)
  fillRect(pixels, size, 16, 28, 4, 4, [255, 100, 100, 255]);
  fillRect(pixels, size, 44, 28, 4, 4, [255, 100, 100, 255]);

  // Tail (lightning bolt)
  fillRect(pixels, size, 46, 32, 8, 4, yellow);
  fillRect(pixels, size, 50, 28, 6, 6, yellow);
  fillRect(pixels, size, 52, 24, 4, 6, yellow);

  // Feet
  fillRect(pixels, size, 22, 50, 6, 6, orange);
  fillRect(pixels, size, 36, 50, 6, 6, orange);

  const png = createPNG(size, size, pixels);
  savePNG(png, 'public/assets/sprites/creatures/sparkit.png');
}

// ============ INTRO TILES ============

function createFloorWoodTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const wood1 = [139, 90, 43, 255];    // Base wood
  const wood2 = [160, 110, 60, 255];   // Lighter wood
  const wood3 = [120, 75, 35, 255];    // Darker wood
  const grain = [100, 60, 25, 255];    // Wood grain

  // Base color
  for (let y = 0; y < TILE_SIZE; y++) {
    for (let x = 0; x < TILE_SIZE; x++) {
      const noise = Math.random();
      if (noise < 0.6) {
        pixels[y * TILE_SIZE + x] = wood1;
      } else if (noise < 0.85) {
        pixels[y * TILE_SIZE + x] = wood2;
      } else {
        pixels[y * TILE_SIZE + x] = wood3;
      }
    }
  }

  // Wood grain lines (horizontal)
  for (let y = 4; y < TILE_SIZE; y += 8) {
    for (let x = 0; x < TILE_SIZE; x++) {
      if (Math.random() > 0.3) {
        pixels[y * TILE_SIZE + x] = grain;
      }
    }
  }

  // Plank separation lines
  for (let x = 0; x < TILE_SIZE; x += 16) {
    for (let y = 0; y < TILE_SIZE; y++) {
      pixels[y * TILE_SIZE + x] = grain;
    }
  }

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/floor_wood.png');
}

function createFloorTileTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const tile1 = [200, 200, 210, 255];  // Light tile
  const tile2 = [180, 180, 195, 255];  // Darker tile
  const grout = [150, 150, 160, 255];  // Grout line

  // Base tile pattern (checkerboard)
  for (let y = 0; y < TILE_SIZE; y++) {
    for (let x = 0; x < TILE_SIZE; x++) {
      const tileX = Math.floor(x / 16);
      const tileY = Math.floor(y / 16);
      const isLight = (tileX + tileY) % 2 === 0;
      pixels[y * TILE_SIZE + x] = isLight ? tile1 : tile2;

      // Add slight noise
      if (Math.random() > 0.9) {
        pixels[y * TILE_SIZE + x] = [
          pixels[y * TILE_SIZE + x][0] + 10,
          pixels[y * TILE_SIZE + x][1] + 10,
          pixels[y * TILE_SIZE + x][2] + 10,
          255
        ];
      }
    }
  }

  // Grout lines
  for (let i = 0; i < TILE_SIZE; i++) {
    pixels[i * TILE_SIZE + 15] = grout;
    pixels[i * TILE_SIZE + 16] = grout;
    pixels[15 * TILE_SIZE + i] = grout;
    pixels[16 * TILE_SIZE + i] = grout;
  }

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/floor_tile.png');
}

function createStairsTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const wood = [139, 90, 43, 255];
  const woodDark = [100, 60, 30, 255];
  const shadow = [80, 50, 25, 255];

  // Fill with dark wood
  for (let i = 0; i < pixels.length; i++) {
    pixels[i] = woodDark;
  }

  // Draw stair steps
  const stepHeight = 8;
  for (let step = 0; step < 4; step++) {
    const y = step * stepHeight;
    const indent = step * 2;

    // Step surface
    for (let sy = y; sy < y + stepHeight - 2; sy++) {
      for (let sx = indent; sx < TILE_SIZE - indent; sx++) {
        if (sy >= 0 && sy < TILE_SIZE && sx >= 0 && sx < TILE_SIZE) {
          pixels[sy * TILE_SIZE + sx] = wood;
        }
      }
    }

    // Step shadow/edge
    for (let sx = indent; sx < TILE_SIZE - indent; sx++) {
      if (y + stepHeight - 2 < TILE_SIZE) {
        pixels[(y + stepHeight - 2) * TILE_SIZE + sx] = shadow;
      }
      if (y + stepHeight - 1 < TILE_SIZE) {
        pixels[(y + stepHeight - 1) * TILE_SIZE + sx] = shadow;
      }
    }
  }

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/stairs.png');
}

function createDoorTile() {
  const pixels = new Array(TILE_SIZE * TILE_SIZE);
  const door = [101, 67, 33, 255];      // Door brown
  const doorDark = [80, 50, 25, 255];   // Darker edge
  const frame = [60, 40, 20, 255];      // Frame
  const handle = [200, 180, 100, 255];  // Gold handle

  // Frame
  fillRect(pixels, TILE_SIZE, 0, 0, TILE_SIZE, TILE_SIZE, frame);

  // Door body
  fillRect(pixels, TILE_SIZE, 3, 2, TILE_SIZE - 6, TILE_SIZE - 3, door);

  // Door panels
  fillRect(pixels, TILE_SIZE, 6, 5, 8, 10, doorDark);
  fillRect(pixels, TILE_SIZE, 18, 5, 8, 10, doorDark);
  fillRect(pixels, TILE_SIZE, 6, 18, 8, 10, doorDark);
  fillRect(pixels, TILE_SIZE, 18, 18, 8, 10, doorDark);

  // Handle
  fillRect(pixels, TILE_SIZE, 22, 15, 3, 3, handle);

  const png = createPNG(TILE_SIZE, TILE_SIZE, pixels);
  savePNG(png, 'public/assets/sprites/tiles/door.png');
}

function createSignSprite() {
  const size = 32;
  const pixels = new Array(size * size).fill([0, 0, 0, 0]);

  const post = [101, 67, 33, 255];     // Brown post
  const board = [222, 184, 135, 255];  // Light board
  const boardEdge = [180, 140, 100, 255];

  // Post
  fillRect(pixels, size, 14, 16, 4, 16, post);

  // Board
  fillRect(pixels, size, 4, 4, 24, 14, board);
  fillRect(pixels, size, 4, 4, 24, 2, boardEdge);
  fillRect(pixels, size, 4, 16, 24, 2, boardEdge);
  fillRect(pixels, size, 4, 4, 2, 14, boardEdge);
  fillRect(pixels, size, 26, 4, 2, 14, boardEdge);

  const png = createPNG(size, size, pixels);
  savePNG(png, 'public/assets/sprites/tiles/sign.png');
}

// ============ UI SPRITES ============

function createPokeballSprite() {
  const size = 32;
  const pixels = new Array(size * size).fill([0, 0, 0, 0]);

  const red = [220, 50, 50, 255];
  const white = [255, 255, 255, 255];
  const black = [30, 30, 30, 255];
  const gray = [100, 100, 100, 255];

  // Top half (red)
  for (let y = 4; y < 16; y++) {
    for (let x = 4; x < 28; x++) {
      const dx = x - 16;
      const dy = y - 16;
      if (dx * dx + dy * dy < 144) {
        pixels[y * size + x] = red;
      }
    }
  }

  // Bottom half (white)
  for (let y = 16; y < 28; y++) {
    for (let x = 4; x < 28; x++) {
      const dx = x - 16;
      const dy = y - 16;
      if (dx * dx + dy * dy < 144) {
        pixels[y * size + x] = white;
      }
    }
  }

  // Middle line
  fillRect(pixels, size, 4, 15, 24, 2, black);

  // Center button
  for (let y = 12; y < 20; y++) {
    for (let x = 12; x < 20; x++) {
      const dx = x - 16;
      const dy = y - 16;
      if (dx * dx + dy * dy < 16) {
        pixels[y * size + x] = white;
      }
      if (dx * dx + dy * dy < 9) {
        pixels[y * size + x] = gray;
      }
    }
  }

  // Outline
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const dx = x - 16;
      const dy = y - 16;
      const dist = dx * dx + dy * dy;
      if (dist >= 144 && dist < 169) {
        pixels[y * size + x] = black;
      }
    }
  }

  const png = createPNG(size, size, pixels);
  savePNG(png, 'public/assets/sprites/ui/pokeball.png');
}

// ============ GENERATE ALL ============

console.log('Generating sprites...\n');

// Tiles
createGrassTile();
createTallGrassTile();
createPathTile();
createWaterTile();
createWallTile();

// Player
createPlayerSprite();

// Creatures
createFlamlingSprite();
createAqualingSprite();
createLeaflingSprite();
createSparkitSprite();

// UI
createPokeballSprite();

// Intro tiles
createFloorWoodTile();
createFloorTileTile();
createStairsTile();
createDoorTile();
createSignSprite();

console.log('\nDone! All sprites generated.');
